# Local Document Search Configuration

# Directory where the index and metadata will be stored
# Now defaults to: ~/Library/Application Support/FinderSemanticSearch/data/index
# index_dir: ./data/index

# Embedding model configuration
# Options: "sentence-transformer" or "ollama"
embedding_model_type: sentence-transformer

# Model name for embeddings
# For sentence-transformer: "all-MiniLM-L6-v2", "all-mpnet-base-v2", etc.
# For ollama: "nomic-embed-text", "mxbai-embed-large", etc.
embedding_model_name: all-MiniLM-L6-v2

# Default number of search results to return
default_search_results: 10

# Document processing settings
chunk_size: 1000  # Number of words per chunk
chunk_overlap: 200  # Overlap between chunks

# Search settings
search_batch_size: 32  # Batch size for processing embeddings

# Cache settings
use_embedding_cache: true
# Now defaults to: ~/Library/Application Support/FinderSemanticSearch/data/embeddings_cache
# embedding_cache_dir: ./data/embeddings_cache