name: CI

on:
  push:
    branches: [main, electron]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-13
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run unit tests
        run: npm run test:unit
      
  build-dmg:
    needs: test
    runs-on: macos-13
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build and package
        run: npm run dist
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
      
      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: mac-dmg
          path: dist-app/*.dmg